// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';
import { createSiteClient } from './supabaseSite';

const SUPABASE_URL = "https://amhlmmzmbjcxzpynnirx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtaGxtbXptYmpjeHpweW5uaXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjEwNzMsImV4cCI6MjA3MDI5NzA3M30.lQ3epSFa-LNWHZ-92HcQbknG4KvsuJXu3oJKJlVLrg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use cookies instead of localStorage so credentials persist securely across refreshes
const cookieStorage = {
  getItem: (key: string) => {
    const match = document.cookie.split('; ').find(row => row.startsWith(`${key}=`));
    return match ? decodeURIComponent(match.split('=')[1]) : null;
  },
  setItem: (key: string, value: string) => {
    document.cookie = `${key}=${encodeURIComponent(value)}; path=/; secure; samesite=strict`;
  },
  removeItem: (key: string) => {
    document.cookie = `${key}=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT`;
  }
};

export const supabase = createSiteClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, undefined, {
  auth: {
    storage: cookieStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});