// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amhlmmzmbjcxzpynnirx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtaGxtbXptYmpjeHpweW5uaXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjEwNzMsImV4cCI6MjA3MDI5NzA3M30.lQ3epSFa-LNWHZ-92HcQbknG4KvsuJXu3oJKJlVLrg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});